Issue 1 create an entry
NolanReda/code-journal pull request #5
Opened 2022-06-01 23:19 UTC by NolanReda

![mobile layout 1](https://user-images.githubusercontent.com/99226300/171517067-805bae82-7a5c-4a30-9f30-895c96ade227.jpg)
![moble layout 2](https://user-images.githubusercontent.com/99226300/171517070-7f7133aa-7cbe-4aca-abd0-14de77c06e8c.jpg)
![desktop blank](https://user-images.githubusercontent.com/99226300/171517073-d9cf1121-eb5e-4204-a6ab-cc82067d4009.jpg)
![desktop filled out](https://user-images.githubusercontent.com/99226300/171517075-a3bbe291-7ed1-41d1-9e72-cbb999485412.jpg)

2022-06-01 23:20 UTC, NolanReda commented
![local storage for feature 1](https://user-images.githubusercontent.com/99226300/171517196-546912b4-ce02-4035-bcf9-d992c85330c9.jpg)

2022-06-01 23:47 UTC, NolanReda commented
![mobile layout 1](https://user-images.githubusercontent.com/99226300/171519488-4b6a5f50-d85a-4a92-8b7b-8c3457e246a3.jpg)
![mobile layout 2](https://user-images.githubusercontent.com/99226300/171519493-8ab315a0-db2d-4283-b8bb-4d44f72c5d4e.jpg)

2022-06-01 23:57 UTC, codingcodymiller requested changes

2022-06-01 23:57 UTC, codingcodymiller commented on css/styles.css
> +  margin: auto;
You can remove these, the `container` class will handle this for you.

2022-06-01 23:57 UTC, codingcodymiller commented on css/styles.css
> +  height: 3.5rem;
You shouldn't set height on elements unless it is absolutely necessary.

2022-06-01 23:57 UTC, codingcodymiller commented on css/styles.css
> +} */
Please delete commented code prior to submitting for review.

2022-06-01 23:57 UTC, codingcodymiller commented on js/main.js
> +  data.nextEntryId++;
You are not preventing the default behavior of the form refreshing the page, and you are not resetting the form.

2022-06-01 23:57 UTC, codingcodymiller commented on js/main.js
> +// var div = document.querySelector('main');
Why do you have code for the next feature? Please delete this, you should not be working ahead.

2022-06-02 00:15 UTC, codingcodymiller approved these changes

2022-06-02 00:16 UTC, merged